---
name: Cargo lint

on:
  push:
  workflow_call:

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v1

  lint:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-15]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.85.0
        with:
          components: rustfmt, clippy

      # Ensure all code has been formatted with rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check --color always

      - name: Tests all targets all features
        run: cargo test --lib --workspace --all-targets --all-features

      - name: Static analysis
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Static analysis all features
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Test doc
        run: cargo test --workspace --all-features --doc

  cargo-publish:
    needs:
      - audit
      - lint
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-publish-workspace.yml@develop
    with:
      toolchain: 1.85.0
    secrets: inherit
